### ISSUE TITLE
Distance vs SINR/Throughput

### ISSUE THREAD

**Issue by DmitarC** [nyuwireless/ns3-mmwave#6] opened 2016-12-21 14:44 UTC
Hi,

could you please explain how did you get results for distance vs SINR graph and distance vs data rates graph in this paper: https://arxiv.org/pdf/1506.08801v1.pdf ?

I tried with mmwave-tdma example, but I get values that are nowhere near yours..

Thank you!

**Comment by rustyolford** [comment] 2016-12-21 15:26
There is a more recent paper which provides some better documentation of
the current version of the module:

http://dl.acm.org/citation.cfm?id=2915380

**Comment by DmitarC** [comment] 2016-12-21 18:28
Thank you for the quick response, rustyolford!
I read the paper, but I still can't figure out the results in the first paper. Are some parameters different from the default ones?

**Comment by DmitarC** [comment] 2016-12-22 10:23
So, here is the command I'm using, but not getting results similar to yours:

$ ./waf --run="scratch/mmwave-tdma --ns3::MmWaveBeamforming::UeSpeed=20 --distMin=40 --distMax=140"

After that, I take 7th column *m_tbsize", sum it per given UE-eNB distance, convert to Gbits and dividide it by distUpdateInterval=100 miliseconds.

Am I missing something?
Am I missing something?

**Comment by zml312570140** [comment] 2016-12-22 16:08
Try to use the mmwave-example.cc and add a mobility model to the UE node. You can set the Propagation loss model to be LoS or NLoS by adding the following commands,

Config::SetDefault ("ns3::MmWavePropagationLossModel::ChannelStates", StringValue (“l")); //LoS
Config::SetDefault ("ns3::MmWavePropagationLossModel::ChannelStates", StringValue ("n")); //NLoS

Then you should be able to reproduce the figure.

**Comment by DmitarC** [comment] 2016-12-22 17:44
From which traces?

**Comment by zml312570140** [comment] 2016-12-22 17:48
From the RxPacketTrace.txt, the 7th column is TB size, the last column is the SINR averaged over the frequency.

**Comment by DmitarC** [comment] 2016-12-22 18:13
Ok, so I've added these lines in the main function in order to simulate this scenario: "_We validate our framework through a simple simulation scenario, where we consider one eNodeB and one UE. The user is  at  an  initial  distance  of  40m  from  the  base  station  and moves towards the cell-edge with a constant velocity of 20 m/s."_   

Config::SetDefault ("ns3::MmWavePropagationLossModel::ChannelStates", StringValue ("n")); 
Config::SetDefault ("ns3::MmWaveBeamforming::UeSpeed", DoubleValue (20));
uePositionAlloc->Add (Vector (40.0, 0.0, 0.0));
uemobility.SetMobilityModel ("ns3::ConstantVelocityMobilityModel");

but still no luck,results are not even comparable to yours.

**Comment by rustyolford** [comment] 2016-12-22 18:21
Okay then, can you attach the example code and output you are getting?

Note that the code has changed a lot since the version used in this paper,
which was over 1.5 years ago.  It may not be possible to reproduce these
simulations exactly using the current code. However, the SINR and rate as a
function of distance should be roughly the same as the original version.

**Comment by rustyolford** [comment] 2016-12-22 18:27
Also I think the small scale fading model either didn't exist or was quite
different at the time of the first MSWiM paper.

So you should set 'smallScale' to false in mmwave-tdma to enable AWGN only.

Also if you read the second paper, it discusses how a pre-computed channel
matrix is randomly assigned to each UE.  It is possible that a different
channel matrices and different LoS/NLoS states are being assigned in the
first paper than what happens currently in the code.

**Comment by DmitarC** [comment] 2016-12-22 18:55
Absolutely, I'm not trying to get exact same values, just something comparable, so I can be sure I'm using it the right way!

I'm attaching mmwave-tdma.cc script ( small scale fading off and uemobility.SetMobilityModel ("ns3::ConstantVelocityMobilityModel") ), RxPacketTrace and output I get on the terminal.

[mmwave-tdma.txt](https://github.com/nyuwireless/ns3-mmwave/files/669573/mmwave-tdma.txt)
[RxPacketTrace_2.txt](https://github.com/nyuwireless/ns3-mmwave/files/669570/RxPacketTrace_2.txt)
[TerminalOutput.txt](https://github.com/nyuwireless/ns3-mmwave/files/669571/TerminalOutput.txt)

**Comment by rustyolford** [comment] 2016-12-22 19:15
The average rate I am getting from your RxPacketTrace.txt file is 3.1 Gbps,
which is comparable to Fig 7d from the MSWiM paper. I calculate this
as 8*sum(tbSize)/simTime where tbSize is the sum of the values in the 7th
column and simTime == 4 seconds.

The variation in the SNR can be generated by
changing ns3::MmWaveBeamforming::LongTermUpdatePeriod to something like 1
second.  Basically, this can be used to generate uncorrelated block fading.

If you are trying to get the NLoS curve, you can set 'channelState' to 'n'
in mmwave-tdma, which will force the path loss model to use the NLoS path
loss formula.

**Comment by DmitarC** [comment] 2016-12-22 20:24
Thank you, that really is similar value to the graph, for LOS scenario. 
However, I get exactly the same values in RxPacketTrace.txt when I call it for NLOS scenario ( by changing Config::SetDefault ("ns3::MmWavePropagationLossModel::ChannelStates", StringValue ("n")); )?
The same happens when I change UeSpeed: 

sudo ./waf --run="scratch/mmwave-tdma --ns3::MmWaveBeamforming::UeSpeed=40 --ns3::MmWavePropagationLossModel::ChannelStates='n'"

Could you please check?

**Closed** 2017-06-07 19:04 UTC
